ingress:
  enabled: true
  className: public
  annotations: 
    kubernetes.io/ingress.class: public
  hosts:
    - host: awe.web.intra.norceresearch.no
      paths:
        - path: /WellBoreArchitecture/webapp
          pathType: Prefix
  tls:
    - secretName: awe-web-tls
      hosts:
        - awe.web.intra.norceresearch.no
